### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by ardenn** [evansmwendwa/python-socialite#11]
**How would this feature be useful?**
Hello @evansmwendwa, any chance you could a contributing guide to the project. I've been experiencing some challenges setting up the project, with it's dependencies.

**Describe the solution you'd like**
Possibly a section of the README that briefly provides a guide on how to contribute, set up the project dependencies.

**Comment by evansmwendwa** [comment]
Sure. This will be updated within the week
